# Usar la imagen oficial de SWI-Prolog
FROM swipl:latest

# Crear directorio de trabajo
WORKDIR /app

# Copiar todos los archivos de tu proyecto
COPY . /app

# Comando de inicio (asegúrate de cambiar "tu_archivo.pl" por el nombre real)
CMD ["swipl", "-s", "server.pl", "-g", "start"]